### PR TITLE
consistent copy for religion, ethnicity and disability

### PR DESCRIPTION
**Pull request by EdwardAndress**
- changes as per advice from Rachel

### CODE REVIEW

**Comment by s-block** [comment]
Can one of the admins verify this patch?

**Comment by s-block** [comment]
Can one of the admins verify this patch?

**Comment by s-block** [comment]
add to whitelist

**Comment by EdwardAndress** [comment]
test this please

**Comment by s-block** [comment]
:+1: keep up the good work!

**Pull request merged**
