### PR TITLE
fix phone number icon bug

### PR DESCRIPTION
**Pull request by axemonkey**

### CODE REVIEW

**Comment by axemonkey** [comment]
@jenkins-moj retest this please

**Comment by axemonkey** [comment]
@jenkins-moj retest this please

**Comment by axemonkey** [comment]
@jenkins-moj retest this please

**Comment by axemonkey** [comment]
@jenkins-moj you fucking cockmunch, retest this please

**Comment by axemonkey** [comment]
@jenkins-moj retest this please

**Comment by tyom** [comment]
LGTM.

**Pull request merged**
