### PR TITLE
Add analytics for errors/warnings

### PR DESCRIPTION
**Pull request by teneightfive**

### CODE REVIEW

**Comment by teneightfive** [comment]
retest this please

**Comment by teneightfive** [comment]
retest this please

**Comment by teneightfive** [comment]
retest this please

**Comment by teneightfive** [comment]
retest this please

**Comment by teneightfive** [comment]
retest this please

**Comment by teneightfive** [comment]
retest this please

**Comment by r4vi** [comment]
retest this please

**Comment by teneightfive** [comment]
retest this please

**Pull request merged**
