### PR TITLE
Upgrade base image and packages

### PR DESCRIPTION
**Pull request by niallcreech**
* OpenSSL needs some security and bug fixes, this change brings in
the newest Phusion base image, which uses xenial

* Update NodeJS to the latest supportable version
There are a number of build failures due to the old version of nodejs
used, specifically const in struct mode errors. This change updates
nodejs to the least change supportable version, the 4.x series.

### CODE REVIEW

**Comment by s-block** [comment]
Can one of the admins verify this patch?

**Comment by s-block** [comment]
Can one of the admins verify this patch?

**Comment by niallcreech** [comment]
Going to check/orchestrate with CLA before doing any of these

**Comment by aliuk2012** [comment]
PR #607 updates the base image

**Pull request closed without merging**
